pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Andrei_Docker_Id'
        DOCKERHUB_REPO = 'andrei1033/classroom_attendance_system'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('check') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Andrei1033/-Ohjelmistotuotantoprojekti-1-TX00EY27-3012.git'
            }
        }

        stage('build') {
            steps {
                dir('Classroom_Attendance_System') {
                    bat 'java -version'
                    bat 'javac -version'
                    bat 'mvn -version'
                    bat 'mvn clean install -B'
                }
            }
        }

        stage('test') {
            steps {
                dir('Classroom_Attendance_System') {
                    bat 'mvn test -B'
                }
            }
        }

         stage('jacoco') {
             steps {
                 dir('Classroom_Attendance_System') {
                     bat 'mvn jacoco:report -B'
                 }
             }
             post {
                 always {
                     jacoco(
                         execPattern: 'Classroom_Attendance_System/target/jacoco.exec',
                         classPattern: 'Classroom_Attendance_System/target/classes',
                         sourcePattern: 'Classroom_Attendance_System/src/main/java'
                     )
                 }
             }
         }

        stage('Build Docker Image') {
            steps {
                script {
                    dir("${env.PROJECT_DIR}") {
                        docker.build("${env.DOCKERHUB_REPO}:${env.DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', env.DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${env.DOCKERHUB_REPO}:${env.DOCKER_IMAGE_TAG}").push()
                        docker.image("${env.DOCKERHUB_REPO}:${env.DOCKER_IMAGE_TAG}").push('latest')
                    }
                }
            }
        }
    }
    }
}