pipeline {
    agent any
    tools {
        maven 'Maven3'
    }
    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Andrei_Docker_Id'
        DOCKERHUB_REPO = 'andrei1033/classroom_attendance_system'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('check') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Andrei1033/-Ohjelmistotuotantoprojekti-1-TX00EY27-3012.git'
            }
        }

        stage('build') {
            steps {
                dir('Classroom_Attendance_System') {
                    bat 'java -version'
                    bat 'javac -version'
                    bat 'mvn -version'
                    // -B (Batch mode) предотвращает зависание Maven в CI-системах
                    bat 'mvn clean install -B'
                }
            }
        }

        stage('test') {
            steps {
                dir('Classroom_Attendance_System') {
                    bat 'mvn test -B'
                }
            }
        }

        stage('jacoco') {
            steps {
                dir('Classroom_Attendance_System') {
                    bat 'mvn jacoco:report'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Classroom_Attendance_System') {
                    script {
                        // Создаем .dockerignore «на лету», чтобы Docker не зависал при сканировании папок
                        writeFile file: '.dockerignore', text: '''
                        .git
                        .gitignore
                        .jenkins
                        '''

                        // Сборка образа (теперь она пройдет мгновенно)
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
}
